theme = [
    ('list-header', '', '', '', '', ''),
    ('list-header-column', '', 'dark green', '', '', 'dark green'),
    ('list-header-column-separator', '', 'dark green', '', '', 'dark green'),
    ('striped-table-row', 'white', 'dark gray', '', 'white', 'g27'),
    ('reveal focus', '', 'dark magenta', 'standout', '', 'dark magenta'),
    ('message status', 'white', 'dark blue', 'standout', 'white', 'dark blue'),
    ('message error', 'white', 'dark red', 'standout', 'white', 'dark red'),
    ('status', 'dark cyan', 'default', '', 'dark cyan', 'default'),
    ('flash off', 'black', 'black', 'standout', 'black', 'black'),
    ('flash on', 'white', 'black', 'standout', 'white', 'black'),
    ('pop_up', 'white', 'black', '', 'white', 'black'),
    ('button action', 'white', 'light red', '', 'white', 'light red'),
    ('button cancel', 'black', 'light gray', '', 'black', 'light gray'),
]
