#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always
#BottomUp
RemoveMake
#SudoLoop
#UseAsk
CombinedUpgrade
CleanAfter
#UpgradeMenu
NewsOnUpgrade
NoWarn = lib32-nvidia-dev-utils-tkg lib32-opencl-nvidia-dev-tkg linux-custom-dave linux-custom-dave-headers nvidia-dev-egl-wayland-tkg nvidia-dev-settings-tkg nvidia-dev-tkg nvidia-dev-utils-tkg opencl-nvidia-dev-tkg

#
# Binary OPTIONS
#
# [bin]
# FileManager = ranger
#MFlags = --skippgpcheck
