set column_ratios 1,1
set preview_images false
set preview_images_method kitty
set show_hidden true
set display_tags_in_all_columns true
set draw_borders both
set draw_progress_bar_in_status_bar true
set mouse_enabled true
set sort_directories_first true
set cd_tab_case smart
set cd_tab_fuzzy true
set display_size_in_main_column true
set vcs_aware true
set colorscheme custom
set clear_filters_on_dir_change true
set unicode_ellipsis true
set tilde_in_titlebar true
map <C-d> shell dragon-drag-and-drop -a -x %p &
