[settings]
set_wallpaper = true
gtk = true
active = 3
light_theme = false
editor = launch_vim
execute_cmd = true
command = theme_update
backend = wal
alpha = 85
smart_sort = true
auto_adjust = false

[keywords]
rng = 125747
loldate = It's Boomtime, the 23rd of Bureaucracy (YOLD 3186)

