[settings]
set_wallpaper = true
gtk = true
active = 3
light_theme = false
editor = size_fix vim
execute_cmd = true
command = theme_update
backend = wal
alpha = 85
smart_sort = false
auto_adjust = false

[keywords]
rng = 518925
loldate = It's Prickle-Prickle, the 35th of Bureaucracy (YOLD 3186)

